title: 'Dev Blog'
description: "A periodical on the art of modern Swift software engineering."
baseurl: "/"
url: "https://dehlen.github.io"

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark
listen_for_clients_preferred_style: true

footer: 'follow me on <a href="https://twitter.com/da_eh">twitter</a> or subscribe to the <a href="https://dehlen.github.io/blog/feed.xml">rss feed</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
