# Name of the Workflow
name: Deploy

# Run this workflow only on push on main branch.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that
# can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that
    # will be executed as part of the job

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build Site 🔧
        run: swift run

      - name: Set Public Folder
        run: |
          mkdir .public
          touch .public/.nojekyll
          cp -r Site/* .public
          mv .public public

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: false
          cname: davidvonk.dev
